package:
  name: pocean-core
  version: "1.1.0"

source:
  path: ../

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - numpy
    - pytz
    - python-dateutil
    - netcdf4
    - pandas
    - pygc >=1.2.0
    - simplejson
    - shapely

test:
  source_files:
    - pocean
  requires:
    - pytest
  imports:
    - pocean
    - pocean.dsg
    - pocean.grid
    - pocean.tests
  commands:
    - py.test pocean

about:
  home: https://github.com/axiom-data-science/pocean-core
  license: MIT
  summary: 'A python framework for working with met-ocean data.'
